packages:
  - "apps/*"
  - "packages/*"
  - "modules/**/*"

allowBuilds:
  argon2: set this to true or false
  esbuild: true
  msgpackr-extract: true
  msw: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - shadcn@4.8.1
